### ISSUE TITLE
undefined method `force_encoding' in ruby 1.8

### ISSUE THREAD

**Issue by imanel** [markjeee/Socket.IO-rack#2]
force_encoding is only needed in ruby 1.9 - so in ruby 1.8 they can be skipped.

**Comment by markjeee** [comment]
yep yep, i've been mostly developing this on ruby 1.9.2. haven't tried it on 1.8 yet.

**Comment by markjeee** [comment]
Yo, i see that you made a fork. Just make some fixes and changes and give me a pull request so i can incorporate it. I haven't used it yet on a real world app, planning to do that soon, so i get more experience how it's going to be used. Just started it this last week, and I only have my night shift to work on it. Thanks!

**Comment by imanel** [comment]
I'm planning to base my application on this one so probably I will actively help with developping it. Right now I sent pull request, but it created new ticket(#3) - first time working with new pull system so it's little confusing for me...

**Comment by imanel** [comment]
Merged - closing
